### ISSUE TITLE
Anaconda镜像站帮助中缺少Anaconda3的配置

### ISSUE THREAD

**Issue by Michael1015198808** [tuna/issues#1108]
[Anaconda镜像站使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/)中给出的Anaconda配置为Anaconda2的格式，Anaconda3将.condarc改成了JSON的字典格式，因此不能直接使用帮助中给出的配置。
希望能够增加Anaconda3的.condarc配置。

**Comment by skyzh** [comment]
可以考虑换成用 conda 命令配置。FYI: https://github.com/sjtug/portal/blob/master/content/post/mirror-help/anaconda.md

```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/{{channel}}
```

**Comment by Michael1015198808** [comment]
我通过摸索已经完成了配置，这个issue主要是希望能在帮助页中强调一下那个配置仅适用于Anaconda2，防止不了解Anaconda2和Anaconda3的同学弄混。

**Comment by ZenithalHourlyRate** [comment]
>Anaconda3将.condarc改成了JSON的字典格式，因此不能直接使用帮助中给出的配置。
> 希望能够增加Anaconda3的.condarc配置。

您好，我并未找到相关材料说明 anaconda3 的 condarc 改为了 JSON 字典格式，也并未找到相关材料说明其与旧格式不兼容。经过测试，[Anaconda3-2020.11-Linux-x86_64.sh](https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-2020.11-Linux-x86_64.sh) 版本仍能使用帮助页面中的配置。

**Comment by Michael1015198808** [comment]
抱歉，可能才疏学浅，我的描述可能不太准确。

我查阅了一下我的机器上的`.condarc`，格式如下

```
{changeps1: false, show_channel_urls: true, default_channels: [https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main,
     https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r,
     https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2],
   channels: [https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/, https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/,
     https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/, https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/,
     https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/, defaults]}
```

我重新尝试按照[Anaconda镜像站使用帮助](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/)（以下简称使用帮助）中提供的

```
channels:
  - defaults
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```
格式的`.condarc`进行配置，发现Anaconda3是能够解析的，我之前的遇到问题没有复现。

非常感谢！
