### ISSUE TITLE
[tuna]404 at /anaconda/cloud/paddle

### ISSUE THREAD

**Issue by TankAbraham** [tuna/issues#1159]
#### 发生了什么（What happened）
```bash
$ conda install paddlepaddle==2.0.0 -c paddle
```

报错：
```
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: paddle
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/paddle
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```
#### 期望的现象（What you expected to happen）
希望基于清华源的PaddlePaddle2.0安装成功

#### 如何重现（How to reproduce it）

设置 ~/.condarc 文件内容如下：
```
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults

show_channel_urls: true

default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2

custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：未检索。

#### 您的环境（Environment）
- 操作系统（OS Version）：windows subsystem linux(WSL) ubuntu 20.04
- 浏览器（如果适用）（Browser version, if applicable）：遨游5浏览器
- 其他（Others）：私以为，该问题出现的原因，可能是Paddle清华源的URL路径不正确——URL中的最后一个p字母不应该大写。可能的修改方式如下所示：

```
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ 
修改为
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/paddle/
```

**Comment by skyzh** [comment]
```yaml
custom_channels:
  Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

```bash
conda install paddlepaddle==2.0.0 -c Paddle
```

即可。

**Comment by TankAbraham** [comment]
> ```yaml
> custom_channels:
>   Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
> ```
> 
> ```shell
> conda install paddlepaddle==2.0.0 -c Paddle
> ```
> 
> 即可。

您好！

我已将 ~/.condarc 按照您的建议做了修改，分别常识了两次，仍然不起作用。两次的 ~/.condarc 文件内容如下：

第一次：
```
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

第二次：
```
custom_channels:
  Paddle: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

麻烦您多多指教，感谢！~
