### ISSUE TITLE
Anaconda镜像安装提示warning，存在包冲突

### ISSUE THREAD

**Issue by doupongzeng** [tuna/issues#1176]
#### 发生了什么（What happened）
1. 修改.condarc 为镜像使用帮助提供
```
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```
运行
`conda install -c conda-forge scrapy`
输出有warning，scrapy能够正常安装。
```
Collecting package metadata (current_repodata.json): done
Solving environment: \
Warning: 8 possible package resolutions (only showing differing packages):
  - https://repo.anaconda.com/pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3, https://repo.anaconda.com/pkgs/main/win-64::ca-certificates-2020.10.14-0, https://repo.anaconda.com/pkgs/main/win-64::openssl-1.1.1h-he774522_0
  - defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, https://repo.anaconda.com/pkgs/main/win-64::ca-certificates-2020.10.14-0, https://repo.anaconda.com/pkgs/main/win-64::openssl-1.1.1h-he774522_0
  - defaults/win-64::openssl-1.1.1h-he774522_0, https://repo.anaconda.com/pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3, https://repo.anaconda.com/pkgs/main/win-64::ca-certificates-2020.10.14-0
  - defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::openssl-1.1.1h-he774522_0, https://repo.anaconda.com/pkgs/main/win-64::ca-certificates-2020.10.14-0
  - defaults/win-64::ca-certificates-2020.10.14-0, defaults/win-64::openssl-1.1.1h-he774522_0, https://repo.anaconda.com/pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3
  - defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::ca-certificates-2020.10.14-0, defaults/win-64::openssl-1.1.1h-he774522_0
  - defaults/win-64::ca-certificates-2020.10.14-0, https://repo.anaconda.com/pkgs/main/noarch::certifi-2020.6.20-pyhd3eb1b0_3, https://repo.anaconda.com/pkgs/main/win-64::openssl-1.1.1h-he774522_0
  - defaults/noarch::certifi-2020.6.20-pyhd3eb1b0_3, defaults/win-64::ca-certificates-2020.10.14-0, https://repo.anaconda.com/pkgs/main/win-64::openssl-1.1.1h-he774522done
```
2. 修改.condarc 为 [#985提到的解决办法](https://github.com/tuna/issues/issues/985#issuecomment-699568308)
依然不起作用，报一样的warning
3. 尝试执行 [#719提到的测试](https://github.com/tuna/issues/issues/719#issuecomment-591796004)
进行创建是没有warning的，一切正常

#### 期望的现象（What you expected to happen）
消除warning

#### 如何重现（How to reproduce it）
`conda install -c conda-forge scrapy`

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：
- https://github.com/tuna/issues/issues/985
- https://github.com/tuna/issues/issues/719

#### 您的环境（Environment）
- 操作系统（OS Version）：windows 10
