### ISSUE TITLE
Anaconda镜像配置文件报HTTP000及解决办法

### ISSUE THREAD

**Issue by StCocaine** [tuna/issues#1527]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

在使用贵协会 [[Anaconda 镜像使用帮助]](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/) 过程中，按帮助文档设置好 ”用户目录下的 `.condarc` 文件” 内容后，运行 `conda create -n myenv numpy` 命令出现以下报错：
```c++
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64'
```

### 期望的现象（What you expected to happen）

运行 `conda create -n myenv numpy` 命令后正常解析：
```c++
Collecting package metadata (current_repodata.json): done
Solving environment: done
...
```

### 如何重现此问题（How to reproduce it）

安装 `Anaconda`发行版，按以下内容设置 ”**用户目录下**的 `.condarc` 文件” ：
```
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

之后运行 `conda create -n myenv numpy` 命令

### 操作系统（OS Version）

win10

### 浏览器（如果适用）（Browser version, if applicable）

Chrome 103.0.5060.114 x64

### 其他环境（Other environments）

版本	Windows 10 专业版
版本号	21H2
安装日期	‎2021/‎5/‎9
操作系统内部版本	19044.1826
体验	Windows Feature Experience Pack 120.2212.4180.0

### 其他需要说明的事项（Anything else we need to know）

经测试，将`https`协议变为`http`协议，进行如下设置则正常运行：
```c++
channels:
  - defaults
show_channel_urls: true
default_channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

奇怪的是，配置中保持`https`协议并增加`ssl_verify: true`设置，依然如上出现同样的报错，希望知道具体原因，不甚言谢！

非常感谢贵协会利用宝贵的资源提供珍贵的国内镜像服务，利好国内开发者。另外，最好能对 [[Anaconda 镜像使用帮助]](https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/) 页面中的设置进行修改并增加配置的使用说明，避免后人重蹈覆辙。谢谢辛苦了！
