### ISSUE TITLE
conda同步pytorch相关库，巨慢无比

### ISSUE THREAD

**Issue by hjysmi** [tuna/issues#1610]
### 先决条件 (Prerequisites)

- [X] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

使用如下命令同步pytorch时，113M的cuda-nvvp-11.8.87库同步了20分钟，还是0%，抓包看到在请求https://mirrors.tuna.tsinghua.edu.cn/static/tunasync.json ，帮忙确认下清华镜像里是否存在cuda相关的库呀，还是有其他bug。谢谢

```
 conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia -n env_38
```
![image](https://user-images.githubusercontent.com/13214614/200825673-535a399e-1bf2-48b0-adb5-0508affe963f.png)
![image](https://user-images.githubusercontent.com/13214614/200826940-6d2a2e71-31ea-4ee7-8c64-ee7b3aca8bb8.png)

### 期望的现象（What you expected to happen）

快速的同步pytorch相关库

### 如何重现此问题（How to reproduce it）

```
channels:
  - defaults
show_channel_urls: True
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud

```
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia -n env_38

```

### 操作系统（OS Version）

win10

### 浏览器（如果适用）（Browser version, if applicable）

edge浏览器
