### ISSUE TITLE
CentOS8 Gitlab

### ISSUE THREAD

**Issue by HappyAxin** [tuna/issues#1647]
### 先决条件 (Prerequisites)

- [X] 我已确认这个镜像源从未在 [其他 issues](https://github.com/tuna/issues) 中讨论过。
I am sure that this repo has NEVER been discussed in [other issues](https://github.com/tuna/issues).

- [X] 我已确认这个镜像源没有我选择的镜像站上线。
I am sure that this repo has NOT currently be provided by the sites I select.

- [X] 我已仔细阅读 [请求新镜像前必读（试行）](https://github.com/tuna/issues/issues/741)。
I have CAREFULLY read the [mirroring rules](https://github.com/tuna/issues/issues/741).

### 项目名称与简介 (Project introduction)

CentOS8的gitlab没了！！

### 上游地址与镜像方法 (How to mirror)

https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el8

### 期望上线的镜像站 (Expected mirroring sites)

- [X] TUNA - https://mirrors.tuna.tsinghua.edu.cn
- [X] BFSU - https://mirrors.bfsu.edu.cn
- [X] OpenTUNA - https://opentuna.cn

**Comment by taoky** [comment]
https://github.com/tuna/issues/issues/1560

**Comment by HappyAxin** [comment]
> #1560

好的，谢谢

**Comment by jingjingxyk** [comment]
@HappyAxin  直接用容器，省事
> 创建docker-compose.yaml 文件
```yaml
version: "3"
services:
    gitlab-ce:
        image: gitlab/gitlab-ce:15.5.1-ce.0  # 指定版本比较好
        #    image:  gitlab/gitlab-ce:latest 
        restart: always
        hostname: gitlab
        container_name: gitlab
        volumes:
            - ./etc:/etc/gitlab
            - ./logs:/var/log/gitlab
            - ./data:/var/opt/gitlab
        ports:
            - "80:80"
            - "443:443"
            - "22:22"
 

```

```shell

# 启动
docker-compose -f docker-compose.yaml up -d 
# 关闭
docker-compose -f docker-compose.yaml down --remove-orphans
# 查看日志
docker-compose -f docker-compose.yaml logs -f 
```
