### ISSUE TITLE
Anaconda源无法安装Pytorch

### ISSUE THREAD

**Issue by yiguanxianyu** [tuna/issues#1933]
### 先决条件 (Prerequisites)

- [x] 我已确认这个问题没有在[其他 issues](https://github.com/tuna/issues/issues)中提出过。
I am sure that this problem has NEVER been discussed in [other issues](https://github.com/tuna/issues/issues).

### 发生了什么（What happened）

命令：`conda install pytorch -c pytorch`

`RuntimeError: Unable to read repodata JSON file 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch', error was: repository does not start with an object`

### 期望的现象（What you expected to happen）

正常安装

### 如何重现此问题（How to reproduce it）

.condarc:
```
channels:
  - conda-forge

custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud

show_channel_urls: true
```

新建环境，运行`conda install pytorch -c pytorch`

### 操作系统（OS Version）

Windows 11

### 其他环境（Other environments）

conda 24.3.0
