### ISSUE TITLE
增加Astral uv的PyPI镜像设置指南

### ISSUE THREAD

**Issue by James4Ever0** [tuna/issues#2141]
清华源PyPI现在的帮助文档地址：https://mirror.tuna.tsinghua.edu.cn/help/pypi/

在`~/.config/uv/uv.toml`或者`/etc/uv/uv.toml`填写下面的内容：

```toml
[[index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true
```

具体参考下面的网站：

https://docs.astral.sh/uv/configuration/files/
