### ISSUE TITLE
hackage 镜像帮助页面对于 stack 的配置过时

### ISSUE THREAD

**Issue by tannineo** [tuna/issues#587]
按照hackage的帮助页面在stack的`comfig.yml`中添加设置:
```yaml
package-indices:
  - name: Tsinghua
    download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/package/
    http: http://mirrors.tuna.tsinghua.edu.cn/hackage/00-index.tar.gz
```
执行下面的命令查看stack的bin path， 报错
```shell
$ stack path --local-bin
Could not parse '/Users/cary/.stack/config.yaml':
Aeson exception:
Error in $['package-indices'][0]: failed to parse field 'package-indices': failed to parse field 'hackage-security': key "hackage-security" not present
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```
`config.yml`新增了一些字段，但是帮助页面没有更新。
环境是`osx`
```shell
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

**Comment by tannineo** [comment]
依照错误提示的在线文档增加设置，最后我的`config.yml`如下

```yaml
cat .stack/config.yaml
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
    author-name: tannineo
    author-email: tannineo@outlook.com
    #    copyright:
    github-username: tannineo

setup-info: "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"

urls:
  latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
  lts-build-plans: http://mirrors.tuna.tsinghua.edu.cn/stackage/lts-haskell/
  nightly-build-plans: http://mirrors.tuna.tsinghua.edu.cn/stackage/stackage-nightly/

package-indices:
- name: Tsinghua
  download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/package/
  http: http://mirrors.tuna.tsinghua.edu.cn/hackage/00-index.tar.gz
  hackage-security:
    keyids:
      - 0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d
      - 1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42
      - 280b10153a522681163658cb49f632cde3f38d768b736ddbc901d99a1a772833
      - 2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201
      - 2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3
      - 51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
      - 772e9f4c7db33d251d5c6e357199c819e569d130857dc225549b40845ff0890d
      - aa315286e6ad281ad61182235533c41e806e5a787e0b6d1e7eef3f09d137d2e9
      - fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0
    key-threshold: 3 # number of keys required
    # ignore expiration date, see https://github.com/commercialhaskell/stack/pull/4614
    ignore-expiry: no
# allow-newer: true
```
执行命令解析配置
```shell
$ stack path --local-bin
Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in urls: lts-build-plans, nightly-build-plans
Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in HackageSecurityConfig: http, name
Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in urls: lts-build-plans, nightly-build-plans
Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in HackageSecurityConfig: http, name
/Users/cary/.local/bin
```
虽然有些 warning 提示有冗余字段，算是能通过了。。。
背景是我想自己编译`haskell-language-server`。。。执行`./install.hs build-all`会检查`stack`的配置文件，然后报错，无法开始编译。

**Comment by z4yx** [comment]
您能整理一下并给 tuna/mirror-web 提交pr吗？这样可以帮助到更多人。感谢！

**Comment by Krantz-XRF** [comment]
@tannineo 我使用了跟您几乎一样的配置文件，但是在Windows 10上遇到了`DeleteFile`权限错误。不知道您是否遇到过这个错误，有没有办法解决？我现在不清楚是新版本`stack`的bug还是这个镜像的问题，因为我使用官方源的时候不会出现这种问题。

**Comment by tannineo** [comment]
@z4yz 我放弃使用tuna的stack源了，设置http_proxy走vpn，然后使用官方源。
因为我在编译`haskell/haskell-ide-engine`的时候，有些包没有被找到。
可能是tuna的源没有及时更新。

@Krantz-XRF 因为我对win10环境不熟悉，解决不了这个问题。。。

总之还是翻墙使用官方源比较好。

**Comment by Joejiong** [comment]
> 依照错误提示的在线文档增加设置，最后我的`~/.stack/config.yml`如下
> 
> ```yaml
> # This file contains default non-project-specific settings for 'stack', used
> # in all projects.  For more information about stack's configuration, see
> # http://docs.haskellstack.org/en/stable/yaml_configuration/
> 
> # The following parameters are used by "stack new" to automatically fill fields
> # in the cabal config. We recommend uncommenting them and filling them out if
> # you intend to use 'stack new'.
> # See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
> templates:
>   params:
>     author-name: tannineo
>     author-email: tannineo@outlook.com
>     #    copyright:
>     github-username: tannineo
> 
> setup-info: "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
> 
> urls:
>   latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
>   lts-build-plans: http://mirrors.tuna.tsinghua.edu.cn/stackage/lts-haskell/
>   nightly-build-plans: http://mirrors.tuna.tsinghua.edu.cn/stackage/stackage-nightly/
> 
> package-indices:
> - name: Tsinghua
>   download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/package/
>   http: http://mirrors.tuna.tsinghua.edu.cn/hackage/00-index.tar.gz
>   hackage-security:
>     keyids:
>       - 0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d
>       - 1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42
>       - 280b10153a522681163658cb49f632cde3f38d768b736ddbc901d99a1a772833
>       - 2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201
>       - 2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3
>       - 51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
>       - 772e9f4c7db33d251d5c6e357199c819e569d130857dc225549b40845ff0890d
>       - aa315286e6ad281ad61182235533c41e806e5a787e0b6d1e7eef3f09d137d2e9
>       - fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0
>     key-threshold: 3 # number of keys required
>     # ignore expiration date, see https://github.com/commercialhaskell/stack/pull/4614
>     ignore-expiry: no
> # allow-newer: true
> ```
> 
> 执行命令解析配置
> 
> ```shell
> $ stack path --local-bin
> Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in urls: lts-build-plans, nightly-build-plans
> Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in HackageSecurityConfig: http, name
> Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in urls: lts-build-plans, nightly-build-plans
> Warning: /Users/cary/.stack/config.yaml: Unrecognized fields in HackageSecurityConfig: http, name
> /Users/cary/.local/bin
> ```
> 
> 虽然有些 warning 提示有冗余字段，算是能通过了。。。
> 
> 背景是我想自己编译`haskell/haskell-ide-engine`。
> 编译过程会检查`stack`的配置文件，然后报错，无法开始编译。

好像还是有点问题
我得到以下问题：
Downloading lts-15.6 build plan ...
RedownloadInvalidResponse Request {
  host                 = "mirrors.tuna.tsinghua.edu.cn"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/stackage/lts-haskell//lts-15.6.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 "/Users/name/.stack/build-plan/lts-15.6.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx/1.16.1"),("Date","Fri, 03 Apr "),("Content-Type","text/html; charset=utf-8"),("Content-Length","153"),("Connection","keep-alive"),("Strict-Transport-Security","max-age=31536000"),("X-TUNA-MIRROR-ID","nanomirrors"),("X-TUNA-MIRROR-ID","neomirrors"),("Strict-Transport-Security","max-age=31500")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose})

**Comment by z4yx** [comment]
我们同步的上游是 https://github.com/commercialhaskell/lts-haskell ，里面最新版本只到 14
@dramforever 你了解这个吗，是不是上游不更新git仓库内容了？

**Comment by dramforever** [comment]
https://github.com/tuna/tunasync-scripts/issues/50

gg? 之前看过一下好像忘了，这个可能得跟上游讨论一下

**Comment by ppzzppz** [comment]
修改配置文件后，错误如下
```shell
Warning: /root/.stack/config.yaml: Unrecognized fields in urls: lts-build-plans, nightly-build-plans
Warning: /root/.stack/config.yaml: Unrecognized fields in HackageSecurityConfig: http, name
Stack has not been tested with GHC versions above 8.6, and using 8.8.3, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
Cabal file info not found for aeson-1.4.7.1@sha256:6d8d2fd959b7122a1df9389cf4eca30420a053d67289f92cdc0dbc0dab3530ba,7098, updating
Selected mirror http://mirrors.tuna.tsinghua.edu.cn/hackage/package/
Downloading timestamp
Verification error: Could not deserialize <repo>/timestamp.json: Malformed: (line 1, column 1):
unexpected "<"
expecting white space or JSON value
Downloading root
Could not deserialize <repo>/root.json: Malformed: (line 1, column 1):
unexpected "<"
expecting white space or JSON value
```

**Comment by dramforever** [comment]
```yaml
download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage
```

结尾看起来不应有 `package`

**Comment by ppzzppz** [comment]
去掉package就好了，完成配置如下， 可以跑起来
```
# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
#    author-name:
#    author-email:
#    copyright:
#    github-username:

# The following parameter specifies stack's output styles; STYLES is a
# colon-delimited sequence of key=value, where 'key' is a style name and
# 'value' is a semicolon-delimited list of 'ANSI' SGR (Select Graphic
# Rendition) control codes (in decimal). Use "stack ls stack-colors --basic"
# to see the current sequence.
# stack-colors: STYLES

setup-info: "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"

urls:
  latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
  lts-build-plans: http://mirrors.tuna.tsinghua.edu.cn/stackage/lts-haskell/
  nightly-build-plans: http://mirrors.tuna.tsinghua.edu.cn/stackage/stackage-nightly/

package-indices:
- name: Tsinghua
  download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/
  http: http://mirrors.tuna.tsinghua.edu.cn/hackage/00-index.tar.gz
  hackage-security:
    keyids:
      - 0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d
      - 1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42
      - 280b10153a522681163658cb49f632cde3f38d768b736ddbc901d99a1a772833
      - 2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201
      - 2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3
      - 51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
      - 772e9f4c7db33d251d5c6e357199c819e569d130857dc225549b40845ff0890d
      - aa315286e6ad281ad61182235533c41e806e5a787e0b6d1e7eef3f09d137d2e9
      - fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0
    key-threshold: 3 # number of keys required
    # ignore expiration date, see https://github.com/commercialhaskell/stack/pull/4614
    ignore-expiry: no
```
