### ISSUE TITLE
希望更新一下Anaconda镜像的说明

### ISSUE THREAD

**Issue by chengdi123000** [tuna/issues#620]
对于最新的conda 4.7.11，按下面修改conda channels似乎更易用。

我的`.condarc`文件：
```yaml
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

这样的话，可以在使用形如`conda install -c conda-forge slepc4py`的命令会自动使用tuna的镜像（这些命令是在[https://anaconda.org](https://anaconda.org)上搜索slepc4py时会提示使用的），但是在使用形如`conda install -c cantera cantera`这样不在上述`custom_channels`中的频道（channel）时会依据默认的`channel_alias: https://conda.anaconda.org`去查找包。同时，这样的配置不会导致`channel_priority`错乱，否则经常会莫名其妙地安装conda-forge频道中的非官方的包而非defaults频道中官方使用的包。

另外，目前4.7版本中取消了free频道，在defaults频道中应该只要保留main和r就行了。

reference:
1. https://anaconda.org/conda-forge/slepc4py
2. https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/
