### ISSUE TITLE
清华镜像源教的设置anaconda镜像的方法有误

### ISSUE THREAD

**Issue by LittleFatHero** [tuna/issues#678]
想要将anaconda的镜像改成清华的镜像源，遂按照清华源官方给的方法来设置。
清华源官方给的更改方法连接如下：
https://mirror.tuna.tsinghua.edu.cn/help/anaconda/

一句话，按照上面说的方法，有的软件包根本安装不了，比如py-xgboost软件包。明明就在源里面，却无法使用conda install命令进行安装，提示not available。然后使用老的方法来修改镜像源，即使用如下三个命令来将anaconda源修改成清华源：
```
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
conda config --set show_channel_urls yes
```
然后成功安装了py-xgboost。
因此目前清华源添加anaconda的方法是错误的

**Comment by LittleFatHero** [comment]
目前清华源修改anaconda镜像的方法就是编辑.condarc文件，然后把下面一大堆的东西放到文件里面就：
```
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```
这种做法是错误的，在Windows 10专业版下不行，因此修正方法

**Comment by phy25** [comment]
https://github.com/conda/conda/issues/1757#issuecomment-152560997

不知道有没有帮助呢？

**Comment by LittleFatHero** [comment]
> 
> 
> [conda/conda#1757 (comment)](https://github.com/conda/conda/issues/1757#issuecomment-152560997)
> 
> 不知道有没有帮助呢？

非常感谢您的解答！但是很遗憾，上面的链接对我没有帮助，我不是不知道怎么创建.condarc文件，而是你们给的内容可能是有误的，反正就是不生效，很奇怪

**Comment by phy25** [comment]
@LittleFatHero 首先请留意 GitHub 的显示，我不是 TUNA 的成员。

我在我的 Anaconda 默认安装环境下并不能复现你的问题（Windows）。我看了一下文档，建议你根据 https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html 的说明排查是否其他路径下存在 .condarc，从而 Anaconda 跳过了用户目录下的 .condarc。

```python
 SEARCH_PATH = (
     'C:/ProgramData/conda/.condarc',
     'C:/ProgramData/conda/condarc',
     'C:/ProgramData/conda/condarc.d',
 )
 SEARCH_PATH += (
     '$CONDA_ROOT/.condarc',
     '$CONDA_ROOT/condarc',
     '$CONDA_ROOT/condarc.d/',
     '~/.conda/.condarc',
     '~/.conda/condarc',
     '~/.conda/condarc.d/',
     '~/.condarc',
     '$CONDA_PREFIX/.condarc',
     '$CONDA_PREFIX/condarc',
     '$CONDA_PREFIX/condarc.d/',
     '$CONDARC',
 )
```

的确用 conda config 来做这个的配置可能会更加通用，你自然也可以提交 PR 修改这一帮助文档：https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-anaconda.md

我也留意到文档里以下这种说法其实并不准确，在 Windows 文件管理器里输入 `.condarc.` 即可创建这一文件：

> Windows 用户无法直接创建名为 .condarc 的文件，可先执行 conda config --set show_channel_urls yes 生成该文件之后再修改。

**Comment by wjx0912** [comment]
@LittleFatHero 
试了你的配置（先删掉.condarc，再用你的3个命令），还是不行啊：
conda install -c anaconda  --yes mxnet

完全没有速度。

能帮忙测试下吗。谢谢了

**Comment by LittleFatHero** [comment]
> 
> 
> @LittleFatHero
> 试了你的配置（先删掉.condarc，再用你的3个命令），还是不行啊：
> conda install -c anaconda --yes mxnet
> 
> 完全没有速度。
> 
> 能帮忙测试下吗。谢谢了

你这个用的不是清华源呀，你安装mxnet的命令用的是-c anaconda，意思是从anaconda官方源安装，网速肯定慢的，就算你正确配置了清华源，你的命令强制用官方源了，速度也会很慢。况且，mxnet不应该用conda安装呀，conda安装的是很旧的版本，新版本mxnet不支持conda安装，只能用pip安装

**Comment by wjx0912** [comment]
@LittleFatHero 
谢谢答复。我先改回用pip~

**Comment by KeithTt** [comment]
按照帮助文档设置成这样，发现 `custom_channels` 下的设置都没用，`default_channels` 下的设置可用。

```yaml
channels:
  - defaults
auto_activate_base: false
auto_stack: 1
show_channel_urls: true
channel_priority: false
auto_update_conda: false
override_channels_enabled: true
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
```

我是要安装 `pyngl` 这个包 https://www.pyngl.ucar.edu/Download/ ，只能从 `conda-forge` 这个 channel 获取，但是怎么都获取不到。
