### ISSUE TITLE
anaconda镜像源不起作用

### ISSUE THREAD

**Issue by Sherry520** [tuna/issues#985]
#### 发生了什么（What happened）
安装Miniconda3-latest-Linux-x86_64.sh后，修改镜像源为清华镜像后，安装软件，出来一堆warning
Collecting package metadata (current_repodata.json): done
Solving environment: | 
Warning: >10 possible package resolutions (only showing differing packages):
  - https://repo.anaconda.com/pkgs/main/linux-64/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0,...................................后边还有一堆
都是https://repo.anaconda.com/pkgs开头的，是否意味着这不是清华镜像？？？
#### 期望的现象（What you expected to happen）
希望地址是清华的镜像
#### 如何重现（How to reproduce it）
安装Miniconda3-latest-Linux-x86_64.sh后，修改镜像源为清华镜像后，安装软件
#### 其他事项（Anything else we need to know）
观察到 conda-meta文件中的文件，其中的url都任然为官方镜像地址，为什么没有变成清华的镜像地址呢，是不是有问题？？？？
#### 您的环境（Environment）
- 操作系统（OS Version）：Linux debian-08 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64
- 浏览器（如果适用）（Browser version, if applicable）：
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
您好，请参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/，注意将 `bioconda` 加入到 `custom_channels:`  里面。

**Comment by Sherry520** [comment]
我确实是按照说明修改.condarc文件的，校园网的DNS会对这个造成影响吗？


 
---原始邮件---
发件人: "Miao Wang"<notifications@github.com&gt;
发送时间: 2020年9月26日 13:22:46
收件人: "tuna/issues"<issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Bruce"<1271803144@qq.com&gt;;
主题: Re: [tuna/issues] anaconda镜像源不起作用 (#985)




 
您好，请参考 https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/，注意将 bioconda 加入到 custom_channels:  里面。

**Comment by shankerwangmiao** [comment]
不会，建议把目前完整的 `.condarc` 文件发出来看看

**Comment by Sherry520** [comment]
channels:
&nbsp; - defaults
show_channel_urls: true
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
default_channels:
&nbsp; - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
&nbsp; - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
&nbsp; - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
&nbsp; - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
&nbsp; - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
&nbsp; conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
&nbsp; msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
&nbsp; bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
&nbsp; menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
&nbsp; pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
&nbsp; simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud


 
---原始邮件---
发件人: "Miao Wang"<notifications@github.com&gt;
发送时间: 2020年9月26日 15:05:19
收件人: "tuna/issues"<issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Bruce"<1271803144@qq.com&gt;;
主题: Re: [tuna/issues] anaconda镜像源不起作用 (#985)




 
不会，建议把目前完整的 .condarc 文件发出来看看

**Comment by Sherry520** [comment]
现在问题又变成了网络的问题，查了百度，没解决
(base) liulab@debian-08:~$ conda install -c bioconda fastqc
Collecting package metadata (current_repodata.json): failed


CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64/current_repodata.json&gt;
Elapsed: -


An HTTP error occurred when t


 
---原始邮件---
发件人: "Miao Wang"<notifications@github.com&gt;
发送时间: 2020年9月26日 15:05:19
收件人: "tuna/issues"<issues@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Bruce"<1271803144@qq.com&gt;;
主题: Re: [tuna/issues] anaconda镜像源不起作用 (#985)




 
不会，建议把目前完整的 .condarc 文件发出来看看

**Comment by Sherry520** [comment]
最后把 .condarc 修改成以下内容，就可以正常使用了

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
show_channel_urls: true

**Comment by Michael1015198808** [comment]
> 最后把 .condarc 修改成以下内容，就可以正常使用了，点换成 -
> 
> channels:
> 
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
> * https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
>   custom_channels:
>   conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
>   msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
>   bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
>   menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
>   pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
>   simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
>   show_channel_urls: true

给个小建议，在描述配置的时候，如果想防止`-`之类的符号被渲染，可以写成这样（用三个反引号<kbd>`</kbd>包起来）
```
channels:

- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
- https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  show_channel_urls: true
```
